[2025-09-18T06:26:41.885+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:26:41.894+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:26:41.895+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-09-18T06:26:41.906+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-09-18 06:26:34.314177+00:00
[2025-09-18T06:26:41.913+0000] {standard_task_runner.py:60} INFO - Started process 211 to run task
[2025-09-18T06:26:41.916+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion_dag', 'validate_data', 'manual__2025-09-18T06:26:34.314177+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion_dag.py', '--cfg-path', '/tmp/tmpio12sk65']
[2025-09-18T06:26:41.920+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask validate_data
[2025-09-18T06:26:41.975+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [running]> on host 3aa26d851e1b
[2025-09-18T06:26:42.053+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T06:26:34.314177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T06:26:34.314177+00:00'
[2025-09-18T06:26:42.054+0000] {batch_ingestion_dag.py:57} INFO - Running Great Expectations validation...
[2025-09-18T06:26:42.075+0000] {context_factory.py:398} INFO - Could not find local file-backed GX project
[2025-09-18T06:26:42.077+0000] {base.py:1510} INFO - Created temporary directory '/tmp/tmpp2grovay' for ephemeral docs site
[2025-09-18T06:26:42.078+0000] {config.py:191} INFO - Loading 'datasources' ->
[]
[2025-09-18T06:26:42.157+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/15 [00:00<?, ?it/s]
[2025-09-18T06:26:42.158+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/15 [00:00<?, ?it/s]
[2025-09-18T06:26:42.158+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 2/15 [00:00<00:00, 2428.66it/s]
[2025-09-18T06:26:42.159+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 2/15 [00:00<00:00, 1664.74it/s]
[2025-09-18T06:26:42.159+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  20%|##        | 3/15 [00:00<00:00, 2061.08it/s]
[2025-09-18T06:26:42.159+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  20%|##        | 3/15 [00:00<00:00, 1730.56it/s]
[2025-09-18T06:26:42.161+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  40%|####      | 6/15 [00:00<00:00, 1666.61it/s]
[2025-09-18T06:26:42.161+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  40%|####      | 6/15 [00:00<00:00, 1517.02it/s]
[2025-09-18T06:26:42.166+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 1801.83it/s]
[2025-09-18T06:26:42.166+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 1718.55it/s]
[2025-09-18T06:26:42.166+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 1672.24it/s]
[2025-09-18T06:26:42.167+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 1619.67it/s]
[2025-09-18T06:26:42.178+0000] {batch_ingestion_dag.py:121} INFO - Great Expectations validations passed.
[2025-09-18T06:26:42.179+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-18T06:26:42.191+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=batch_ingestion_dag, task_id=validate_data, execution_date=20250918T062634, start_date=20250918T062641, end_date=20250918T062642
[2025-09-18T06:26:42.251+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-18T06:26:42.280+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
