[2025-09-18T06:37:05.672+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:37:05.678+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:37:05.679+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-09-18T06:37:05.688+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-09-18 06:26:34.314177+00:00
[2025-09-18T06:37:05.693+0000] {standard_task_runner.py:60} INFO - Started process 558 to run task
[2025-09-18T06:37:05.696+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion_dag', 'validate_data', 'manual__2025-09-18T06:26:34.314177+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion_dag.py', '--cfg-path', '/tmp/tmpmo69mku4']
[2025-09-18T06:37:05.698+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask validate_data
[2025-09-18T06:37:05.738+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_ingestion_dag.validate_data manual__2025-09-18T06:26:34.314177+00:00 [running]> on host 3aa26d851e1b
[2025-09-18T06:37:05.805+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T06:26:34.314177+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T06:26:34.314177+00:00'
[2025-09-18T06:37:05.806+0000] {batch_ingestion_dag.py:57} INFO - Running Great Expectations validation...
[2025-09-18T06:37:05.818+0000] {context_factory.py:398} INFO - Could not find local file-backed GX project
[2025-09-18T06:37:05.819+0000] {base.py:1510} INFO - Created temporary directory '/tmp/tmp3rbryimw' for ephemeral docs site
[2025-09-18T06:37:05.820+0000] {config.py:191} INFO - Loading 'datasources' ->
[]
[2025-09-18T06:37:05.862+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/15 [00:00<?, ?it/s]
[2025-09-18T06:37:05.862+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/15 [00:00<?, ?it/s]
[2025-09-18T06:37:05.863+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 2/15 [00:00<00:00, 3274.24it/s]
[2025-09-18T06:37:05.863+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 2/15 [00:00<00:00, 2319.86it/s]
[2025-09-18T06:37:05.863+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  20%|##        | 3/15 [00:00<00:00, 2899.29it/s]
[2025-09-18T06:37:05.863+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  20%|##        | 3/15 [00:00<00:00, 2519.61it/s]
[2025-09-18T06:37:05.865+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  40%|####      | 6/15 [00:00<00:00, 2451.38it/s]
[2025-09-18T06:37:05.865+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  40%|####      | 6/15 [00:00<00:00, 2241.74it/s]
[2025-09-18T06:37:05.867+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 3321.78it/s]
[2025-09-18T06:37:05.867+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 3167.11it/s]
[2025-09-18T06:37:05.867+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 3068.25it/s]
[2025-09-18T06:37:05.867+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 15/15 [00:00<00:00, 2968.93it/s]
[2025-09-18T06:37:05.875+0000] {batch_ingestion_dag.py:121} INFO - Great Expectations validations passed.
[2025-09-18T06:37:05.875+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-18T06:37:05.883+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=batch_ingestion_dag, task_id=validate_data, execution_date=20250918T062634, start_date=20250918T063705, end_date=20250918T063705
[2025-09-18T06:37:05.908+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-18T06:37:05.926+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
