[2025-09-18T06:37:02.915+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion_dag.extract_mysql manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:37:02.921+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion_dag.extract_mysql manual__2025-09-18T06:26:34.314177+00:00 [queued]>
[2025-09-18T06:37:02.921+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-09-18T06:37:02.931+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract_mysql> on 2025-09-18 06:26:34.314177+00:00
[2025-09-18T06:37:02.937+0000] {standard_task_runner.py:60} INFO - Started process 541 to run task
[2025-09-18T06:37:02.940+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion_dag', 'extract_mysql', 'manual__2025-09-18T06:26:34.314177+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion_dag.py', '--cfg-path', '/tmp/tmpo2jz_pau']
[2025-09-18T06:37:02.943+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask extract_mysql
[2025-09-18T06:37:02.984+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_ingestion_dag.extract_mysql manual__2025-09-18T06:26:34.314177+00:00 [running]> on host 3aa26d851e1b
[2025-09-18T06:37:03.043+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion_dag' AIRFLOW_CTX_TASK_ID='extract_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T06:26:34.314177+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T06:26:34.314177+00:00'
[2025-09-18T06:37:03.044+0000] {batch_ingestion_dag.py:26} INFO - Starting extraction from MySQL...
[2025-09-18T06:37:03.045+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-18T06:37:03.045+0000] {base.py:83} INFO - Using connection ID '***_db' for task execution.
[2025-09-18T06:37:03.055+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:215 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-18T06:37:03.065+0000] {batch_ingestion_dag.py:31} INFO - Extracted 5 records from MySQL and saved to /tmp/orders.csv.
[2025-09-18T06:37:03.084+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-18T06:37:03.092+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=batch_ingestion_dag, task_id=extract_mysql, execution_date=20250918T062634, start_date=20250918T063702, end_date=20250918T063703
[2025-09-18T06:37:03.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-18T06:37:03.133+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
